### ISSUE TITLE
Url is forgotten after iyo login

### ISSUE THREAD

**Issue by arahmanhamdy** [Incubaid/gitea-kanban#16]
when login into IYO the url is forgotten, so have to follow url 2x, super annoying of different swim lanes are followed

**Comment by arahmanhamdy** [comment]
It was a caddy related issue and was fixed in this commit https://github.com/itsyouonline/caddy-integration/commit/591de8795211e4d316c7a9bf5e875962e826ebe3

**Comment by Dinaamagdy** [comment]
solved on https://kanban.greenitglobe.com/?stages=
