### ISSUE TITLE
correlate selected repos to labels and milestone filters 

### ISSUE THREAD

**Issue by arahmanhamdy** [Incubaid/gitea-kanban#17]
only labels & milestones should be shown which are part of the chosen repo's, today its all making it rather impossible to filter properly

**Comment by arahmanhamdy** [comment]
Fixed https://github.com/Incubaid/gitea-kanban/commit/d5ba9193e53840ae53b7187f1db1792f01bfdf9e

**Comment by Dinaamagdy** [comment]
fixed on https://kanban.greenitglobe.com/?stages=
