### ISSUE TITLE
hits wrong API endpoint

### ISSUE THREAD

**Issue by mario-mazo** [Incubaid/gitea-kanban#20]
Hello
I tried to set up this
I have gate running go vcs.domain.com and gitea-kanban on cm.domain.com
I added cars to vcs to allow cm
but now I get this error a 404 when trying to connect here

https://vcs.domain.com/api/v1/kanban/filters?token=7a621a2267457b1dcf5923b69d2cc69843279

that api endpoint doesnt exist.

any tips? what am I doing wrong

thanks

**Comment by arahmanhamdy** [comment]
The kanban depends on gitea fork:
https://github.com/gigforks/gitea/tree/iyo_integration

which includes integration with itsyou.online, so it won't work with the normal gitea binaries
