### ISSUE TITLE
map columns values to names in the url

### ISSUE THREAD

**Issue by khaledkbadr** [Incubaid/gitea-kanban#7]
we can set columns values in the URL like this now `stages=backlog,in-progress,question,validation,done` but the problem of that is the inflexibility to have column names different than label values. Suggested approach is to add a mapping to the URL like that `stages=in-progress:state_inprogress` which will map the `state_inprogress` label value to `in-progress` as a column value.

**Comment by Dinaamagdy** [comment]
## Software version 
1a3ad7c088bb7a69631c87a15ae76f1d47a92a8f
