### ISSUE TITLE
Add docs to the repo

### ISSUE THREAD

**Issue by arahmanhamdy** [Incubaid/gitea-kanban#8]
Docs for building/deployment/usage should be added

**Comment by Dinaamagdy** [comment]
need to change there https://github.com/Incubaid/gitea-kanban (Authentication using itsyou.online) to  as example  (Running Kanban with its youonline)

**Comment by Dinaamagdy** [comment]
## Software Version 
1a3ad7c088bb7a69631c87a15ae76f1d47a92a8f
